name: Setup Workspace
description: Checkout and install all dependencies

runs:
  using: composite
  steps:
  - uses: actions/setup-java@v5
    with:
      distribution: temurin
      java-version: 21
      cache: gradle

  - uses: astral-sh/setup-uv@v8.1.0
    with:
      python-version: 3.14
      enable-cache: true

  - uses: pnpm/action-setup@v6
    with:
      version: 11

  - uses: actions/setup-node@v6
    with:
      node-version: lts/*
      cache: pnpm

  - uses: extractions/setup-just@v4

  - shell: bash
    run: just install true
