[versions]
java-compile = "21"
java-support = "8"
kotlin = "2.3.20"
dokka = "2.2.0"
junit = "5.14.3"
ktlint = "1.8.0"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.9.8"
ktlint-gradle = "org.jlleitschuh.gradle.ktlint:14.2.0"
maven-publish = "com.vanniktech.maven.publish.base:0.36.0"
git-publish = "org.ajoberstar.git-publish:6.0.0"
pages = "com.hanggrian.pages:0.3"

[libraries]
# lint
rulebook-ktlint = "com.hanggrian.rulebook:rulebook-ktlint:0.2"
# main
kotlinpoet = "com.squareup:kotlinpoet:1.18.1"
# test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.14.3"
mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.23.0"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:6.2.3"
truth = "com.google.truth:truth:1.4.5"

[bundles]
junit5 = [
  "junit-jupiter",
  "mockito-junit-jupiter",
  "mockito-kotlin",
  "truth",
]
