name: code-analysis

on: [push, pull_request]

env:
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle/
  GRADLE_OPTS: -Dorg.gradle.daemon=false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - run: |
          ./gradlew ktlintCheck
          uv run poe lint
          pnpm lint

  upload-coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-workspace

      - run: ./gradlew koverXmlReport

      - if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
